<?php
/**
 * SPDX-FileCopyrightText: 2016 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
return array (
  'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz' => true,
  'you_have_been_hacked_gwsxh1fzfr' => true,
  'you_have_been_hacked_3latqckh8c' => true,
  'yager15839cloyv72fisk276394jklz' => true,
  'thewoodenperson002071333polenov' => true,
  'taylorad02c2d60a96819341f20824e' => true,
  'starwarsautosejecutivosdearagua' => true,
  'sparkyeduardo_fernando_zornitta' => true,
  'snowboardextremobajistatrujillo' => true,
  'pepperpentium4overclockedtoofar' => true,
  'paxiaomageivan_v_amerike;lerarr' => true,
  'passworaafsfrgsfsef.sfefdfefsaf' => true,
  'oberschopsloan_jtaylorswiftfan1' => true,
  'nightmare29d03m1990ynightq3dm17' => true,
  'newdividwhosyourdaddykoshka1998' => true,
  'maverickeclipse.eclipse.eclipse' => true,
  'jordanbigboydatinh_k0khocvigirl' => true,
  'jenniferanaesthernovias.caceres' => true,
  'i0love1natali0with5all0my9heart' => true,
  'heymakarena12345678900987654321' => true,
  'georgebusram_ali_yerine_sevemem' => true,
  'dyegothiele82310236649994710600' => true,
  'davidsancorrosionofconformity_6' => true,
  'danielsmilesmilesmilesmilesmile' => true,
  'customcslaraalternativelighting' => true,
  'chelseathe_stig_eats_audi_loops' => true,
  'chelseasirotaelenaaleksandrovna' => true,
  'chelseapipinidze.kapysta.avrora' => true,
  'chelseajean.pierre.demeulenaere' => true,
  'batmanelectronics.onlinelimited' => true,
  'ashleynadyanadyanadyanadyanadya' => true,
  'any23609879kostikkolesnikovlove' => true,
  'animalityn0mic477683aptem477683' => true,
  'andreadragon_de-los_ojos_rojos_' => true,
  'amordaminhavidadeustodopoderoso' => true,
  'alejandromossivelasquezbateria2' => true,
  'ps.0mg_rtt_t0rr3ntz_plz_080601;' => true,
  'julia181julia153anisa8alibina15' => true,
  'amordeusverumorbissine415aureum' => true,
  '3544764253634242345465247andrey' => true,
  '020pooh123artificialsarcophagus' => true,
);